version: '2.2'

services:

  ###################
  # Main containers #
  ###################

  web:
    build: .
    environment:
      FLASK_DEBUG: 1
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "plusone"
      DATABASE_HOST: "mysql"
      SECRET_KEY: "aVeryLongSecretKeyShouldBePutHere"
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy

  ########################
  # Auxiliary Containers #
  ########################

  mysql:
    image: mysql:5.7.21
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "plusone"
    ports:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 6

#####################
# Auxiliary Volumes #
#####################

volumes:
  mysql-data:
    driver: local
